#!/usr/bin/zsh
alias reload="source ~/.zshrc"
alias zconf="vim ~/.zshrc"
alias vconf="vim ~/.vimrc"
alias gvconf="vim ~/.gvimrc"

alias v="vim"
alias gv="mvim"
alias b="bundle"
alias be="bundle exec"

alias ls="ls --color"
alias time="noglob time -p"

#-----
# Git
#-----
alias g="git"
alias ga="git add"
alias gb="git branch"
alias gco="git checkout"
alias gd="git diff"
alias gdc="git diff --cached"
alias gst="git status"
alias glo="git log --oneline --decorate"
alias gp="git pull --rebase origin "
alias prunegit='git remote prune origin && git gc --prune=now && git gc --aggressive && git tag -l | xargs git tag -d && git fetch --tags'

# Suffix aliases, 'open with...'
alias -s rb=vim
alias -s log="tail -f"

#-----------
# Shortcuts
#-----------
alias code="cd ~/code"
alias ctagsr="ctags -R --exclude=log --exclude=coverage --exclude=.git -h 'rb.js.coffee.scss.html.haml.yml' -f .tags -f tags &> /dev/null"
alias bu="cd $HOME && brew up --rebase && cd -"
